/* Derived genomes are artistic crossovers; immutable reference sources remain separate. */
(() => {
'use strict';
const F=Object.freeze,KEY='microculture.offspring.v1',ARCHIVE='microculture.archive.v2';let entries=new Map(),loaded=false,storageError=null,saveTimer=null;
function hash(text){let h=2166136261;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
function identity(c){return c.uid||`reference-${c.seed}-${c.specimenIndex??c.id}`;}
function freeze(value){if(!value||typeof value!=='object'||Object.isFrozen(value))return value;for(const v of Object.values(value))freeze(v);return F(value);}
function sources(c){if(c.provenance?.sources?.length)return c.provenance.sources;const source=globalThis.MicroSources?.get(c.specimenIndex??c.id);return source?[{theme:source.theme,symbol:source.symbol,species:source.species,references:source.references,weight:1}]:[];}
function contributions(a,b,weight){const combined=new Map();for(const [parent,fraction] of [[a,weight],[b,1-weight]])for(const source of sources(parent)){const key=source.species||source.theme,previous=combined.get(key),amount=(source.weight??1)*fraction;combined.set(key,{...source,weight:(previous?.weight||0)+amount});}return [...combined.values()];}
function genomicGeneration(c){return Number.isSafeInteger(c.genomicGeneration)&&c.genomicGeneration>=0?c.genomicGeneration:c.derivation?1:0;}
function builder(a,b,options={}){
 const seed=hash(`${identity(a)}|${identity(b)}|${options.nonce||0}`),id=options.id??0,time=options.time??0;
 const specimenIndex=seed%25,baseLayers=MicroFungus.createLayers(seed,specimenIndex,{metadataOnly:true}),weightA=a.layers.reduce((n,l)=>n+Math.max(.01,l.activity),0),weightB=b.layers.reduce((n,l)=>n+Math.max(.01,l.activity),0),weight=weightA/(weightA+weightB);
 function layer(i){const l=baseLayers[i],aa=a.layers[i%25],bb=b.layers[(i*7+3)%25],genome=MicroGenetics.breed(aa.genome,bb.genome,(seed+Math.imul(i+1,104729))>>>0);return F({...l,genome,growthRate:genome.growthRate,branching:genome.branchingRate,activity:aa.activity*weight+bb.activity*(1-weight)});}
 const ancestry=F([{uid:identity(a),weight},{uid:identity(b),weight:1-weight}].map(F));
 const uid=`offspring-${seed.toString(16).padStart(8,'0')}-${hash(`${seed}:identity`).toString(16).padStart(8,'0')}`;
 function finish(layers){const raw=MicroFungus.createColony(seed,specimenIndex,time,{layers});return assemble(raw,{id,specimenIndex,uid,seed,layers,ancestry,genomicGeneration:1+Math.max(genomicGeneration(a),genomicGeneration(b)),rowKey:options.rowKey||(Number.isInteger(options.tileRow)&&globalThis.MicroLayout?MicroLayout.keyAt(options.tileRow):undefined),tileRow:options.tileRow,tileCol:options.tileCol,provenance:{sources:contributions(a,b,weight),kind:'synthetic-derived'},derivation:{kind:'synthetic-crossover',parents:ancestry,parentSequences:[a.layers.map(l=>l.genome.sequence),b.layers.map(l=>l.genome.sequence)],algorithm:'codon-crossover-v2',topologyVersion:'topology-genome-v2',seed,nonce:options.nonce||0,originalReferencesPreserved:true}});}
 return {layer,finish};
}
function create(a,b,options={}){const work=builder(a,b,options);return work.finish(Array.from({length:25},(_,i)=>work.layer(i)));}
function pauseTask(){return new Promise(resolve=>globalThis.setTimeout?setTimeout(resolve,0):resolve());}
async function createAsync(a,b,options={}){const work=builder(a,b,options),layers=[],now=()=>globalThis.performance?.now?.()||0;for(let start=0;start<25;start+=4){if(options.signal?.aborted){const error=new Error('Generation canceled');error.name='AbortError';throw error;}const begun=now();for(let i=start;i<Math.min(start+4,25);i++)layers.push(work.layer(i));options.onTask?.({phase:'breed',layers:Math.min(4,25-start),duration:now()-begun});await pauseTask();}if(options.signal?.aborted){const error=new Error('Generation canceled');error.name='AbortError';throw error;}const begun=now(),child=work.finish(layers);options.onTask?.({phase:'bootstrap',duration:now()-begun});return child;}

function assemble(raw,metadata){const id=metadata.id??raw.id,offset=(id-raw.id)*100000,remap=n=>n==null?n:n+offset;const layers=metadata.layers.map((l,i)=>F({...raw.layers[i],...l,id:i,population:raw.layers[i].population})),genomes=layers.map(l=>l.genome);return freeze({...raw,...metadata,layers,lineages:genomes,genome:genomes[0],nextId:remap(raw.nextId),segments:raw.segments.map(s=>({...s,id:remap(s.id),parentId:remap(s.parentId),targetId:remap(s.targetId),genome:genomes[s.lineage],lifespan:genomes[s.lineage].lifespan,pitch:genomes[s.lineage].pitch})),tips:raw.tips.map(t=>({...t,id:remap(t.id),segmentId:remap(t.segmentId),genome:genomes[t.lineage]}))});}
function recipe(c){return {uid:c.uid,seed:c.seed,specimenIndex:c.specimenIndex,generationTrace:c.generationTrace,genomicGeneration:genomicGeneration(c),rowKey:c.rowKey||`base:${c.tileRow}`,tileRow:c.tileRow,tileCol:c.tileCol,layers:c.layers.map(l=>({seed:l.seed,family:l.family,genome:l.genome})),ancestry:c.ancestry,provenance:c.provenance,derivation:c.derivation};}
function valid(r){return r&&/^offspring-[a-f0-9]+-[a-f0-9]+$/.test(r.uid)&&Number.isInteger(r.seed)&&r.seed>=0&&r.seed<=4294967295&&Number.isSafeInteger(r.tileRow)&&Number.isSafeInteger(r.tileCol)&&Math.abs(r.tileRow)<1e8&&Math.abs(r.tileCol)<1e8&&r.layers?.length===25&&r.layers.every(l=>Number.isInteger(l.seed)&&Number.isInteger(l.family)&&l.family>=0&&l.family<3&&/^[ACGT]{384}$/.test(l.genome?.sequence||'')&&Number.isFinite(l.genome.hue)&&l.genome.hue>=0&&l.genome.hue<360&&Number.isFinite(l.genome.lightness)&&l.genome.lightness>0&&l.genome.lightness<1&&Number.isFinite(l.genome.chroma)&&l.genome.chroma>=0&&l.genome.chroma<.5)&&r.ancestry?.length===2&&r.ancestry.every(p=>typeof p.uid==='string'&&p.uid.length<150&&Number.isFinite(p.weight)&&p.weight>=0&&p.weight<=1)&&Math.abs(r.ancestry.reduce((n,p)=>n+p.weight,0)-1)<1e-8&&r.provenance?.kind==='synthetic-derived'&&Array.isArray(r.provenance.sources)&&r.provenance.sources.length<=64&&r.derivation?.kind==='synthetic-crossover';}
function normalized(r){if(globalThis.MicroLayout)MicroLayout.position(r.rowKey||`base:${r.tileRow}`);return {...r,genomicGeneration:genomicGeneration(r),layers:r.layers.map(l=>({...l,genome:{lightness:l.genome.lightness,chroma:Math.min(l.genome.chroma,MicroColor.ceiling(l.genome.lightness,l.genome.hue)),hue:l.genome.hue,...MicroGenetics.analyze(l.genome.sequence),synthetic:true,translationTable:1,sources:Array.isArray(l.genome.sources)?l.genome.sources:[],generationTrace:l.genome.generationTrace||{version:'legacy-preserved-v1',fingerprint:MicroGenetics.fingerprint(l.genome.sequence)}}}))};}
function lookup(accession,start){for(let i=0;i<25;i++){const reference=globalThis.MicroSources?.get(i)?.references?.find(r=>r.accession===accession&&r.start===start);if(reference)return reference;}return null;}
function encode(key,value){return value?.accession&&/^[a-f0-9]{64}$/i.test(value.checksum||'')&&lookup(value.accession,value.start)?{$source:value.accession,start:value.start}:value;}
function decode(key,value){if(!value?.$source)return value;const source=lookup(value.$source,value.start);if(!source)throw new Error('Reference catalog does not match saved archive');return source;}
function load(){if(loaded)return;loaded=true;try{const archive=JSON.parse(globalThis.localStorage?.getItem(ARCHIVE)||'null',decode);if(archive&&archive.version!==2)throw new Error('Invalid archive version');if(archive?.reveals&&globalThis.MicroAtlas)MicroAtlas.restoreReveals(archive.reveals);if(archive?.layout&&globalThis.MicroLayout)MicroLayout.restore(archive.layout);const records=archive?.records||JSON.parse(globalThis.localStorage?.getItem(KEY)||'[]',decode);if(!Array.isArray(records))throw new Error('Invalid offspring archive');for(const r of records){if(valid(r))entries.set(r.uid,{recipe:freeze(normalized({...r,rowKey:r.rowKey||`base:${r.tileRow}`})),colony:null});else throw new Error('Invalid offspring archive entry');}}catch(error){storageError=String(error.message||error);}}
function flush(){saveTimer=null;try{const records=[...entries.values()].map(v=>v.recipe);if(globalThis.MicroLayout)globalThis.localStorage?.setItem(ARCHIVE,JSON.stringify({version:2,layout:MicroLayout.state(),records,reveals:globalThis.MicroAtlas?.revealState?.()||[]},encode));else globalThis.localStorage?.setItem(KEY,JSON.stringify(records,encode));storageError=null;}catch(error){storageError=String(error.message||error);if(globalThis.dispatchEvent&&globalThis.CustomEvent)globalThis.dispatchEvent(new CustomEvent('microculture-storage-error',{detail:storageError}));}return !storageError;}
function scheduleFlush(){if(globalThis.setTimeout){if(saveTimer!==null)clearTimeout(saveTimer);saveTimer=setTimeout(flush,80);}else flush();}function save(c){load();entries.set(c.uid,{recipe:freeze(recipe(c)),colony:c});scheduleFlush();return !storageError;}
function retain(c){if(!c.derivation)return;load();const old=entries.get(c.uid);if(old)entries.set(c.uid,{...old,colony:c});const live=[...entries].filter(([,v])=>v.colony);for(const [uid,value] of live.slice(0,Math.max(0,live.length-8)))entries.set(uid,{...value,colony:null});}
function find(row,col,id,time){load();for(const v of entries.values()){const r=v.recipe;const visual=globalThis.MicroLayout?MicroLayout.position(r.rowKey||`base:${r.tileRow}`):r.tileRow;if(visual!==row||r.tileCol!==col)continue;if(v.colony){const c=v.colony,offset=(id-c.id)*100000,remap=n=>n==null?n:n+offset;return freeze({...c,id,tileRow:visual,rowKey:r.rowKey,nextId:remap(c.nextId),segments:c.segments.map(s=>({...s,id:remap(s.id),parentId:remap(s.parentId),targetId:remap(s.targetId)})),tips:c.tips.map(t=>({...t,id:remap(t.id),segmentId:remap(t.segmentId)}))});}return assemble(MicroFungus.createColony(r.seed,r.specimenIndex??r.seed%25,time,r.derivation.topologyVersion==='topology-genome-v2'?{layers:r.layers}:{legacy:true}),{...r,id,tileRow:visual});}return null;}
globalThis.MicroOffspring=F({create,createAsync,save,flush,scheduleFlush,retain,find,records:()=>{load();return [...entries.values()].map(v=>v.recipe);},storageError:()=>storageError});
})();
