const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({...require('./browser-support.cjs').launchOptions,headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:2,acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(require('./browser-support.cjs').appURL());await page.waitForFunction(()=>MicroRender.stats().textures>0);await page.waitForTimeout(700);await page.locator('#play').click();
 const runtime=await page.evaluate(()=>({gpu:typeof MicroGPU,sphere:typeof MicroSphere,worker:MicroGeneration.stats(),render:MicroRender.stats()}));assert.equal(runtime.gpu,'undefined');assert.equal(runtime.sphere,'undefined');assert.equal(runtime.worker.backend,'worker');assert(runtime.worker.completed>=25);assert.equal(runtime.render.backend,'canvas');
 const downloadPromise=page.waitForEvent('download');await page.locator('#save').click();const file=await downloadPromise,bytes=fs.readFileSync(await file.path());assert.equal(bytes.readUInt32BE(16),3840);assert.equal(bytes.readUInt32BE(20),2160);
 await page.mouse.move(700,500);await page.mouse.wheel(0,650);await page.waitForFunction(()=>!MicroAtlas.pending()&&!MicroRender.busy());assert((await page.evaluate(()=>MicroGeneration.stats().completed))>runtime.worker.completed);
 await page.locator('#field').press('Enter');await page.waitForFunction(()=>document.body.dataset.stage==='2');const exportDish=page.waitForEvent('download');await page.locator('#dish-save').click();const dish=fs.readFileSync(await (await exportDish).path());assert.equal(dish.readUInt32BE(16),3840);assert.equal(dish.readUInt32BE(20),2160);
 assert.deepEqual(errors,[]);const fallback=await browser.newPage();await fallback.addInitScript(()=>{window.Worker=class {constructor(){throw new Error('Worker unavailable');}};});await fallback.goto(require('./browser-support.cjs').appURL());await fallback.waitForFunction(()=>MicroRender.stats().textures>0);assert.match(await fallback.evaluate(()=>MicroGeneration.stats().error),/Worker unavailable/);await fallback.locator('#play').click();await fallback.close();console.log('PASS worker startup, petri-only runtime, async navigation generation, and both 4K exports');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
