const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const c=vm.createContext({});
for(const name of ['colors.js','biology.js','genetics.js','field.js','fungal.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',name),'utf8'),c);
const F=c.MicroFungus,plain=x=>JSON.stringify(x);
function check(w){assert.ok(Object.isFrozen(w));assert.equal(w.colonies.length,25);for(const k of w.colonies){assert.equal(k.lineages.length,25);assert.ok(Object.isFrozen(k.segments));assert.ok(k.segments.length<=400);assert.ok(k.tips.length<=72&&k.tips.length>=50);assert.equal(new Set(k.tips.map(t=>t.segmentId)).size,k.tips.length);assert.ok(k.nutrients.every(n=>n>=0&&n<=1&&Number.isFinite(n)));for(const s of k.segments){assert.ok(Object.isFrozen(s));assert.ok(Math.hypot(s.xx,s.yy)<=.880001);assert.ok(s.genome.chroma<=c.MicroColor.ceiling(s.genome.lightness,s.genome.hue)+.00001);assert.ok(F.health(s,w.time)>=0&&F.health(s,w.time)<=1);}}}
test('25 deterministic compounds each combine twenty five independently seeded layers',()=>{const a=F.create(8),b=F.create(8);assert.equal(plain(a),plain(b));check(a);for(const k of a.colonies){assert.equal(new Set(k.layers.map(l=>l.seed)).size,25);assert.ok(k.segments.length>=100);assert.ok(k.tips.length>=50);}});
test('apical extension is immutable, paused time is identity, interpolation settles',()=>{const a=F.create(8),snapshot=plain(a);assert.equal(F.advance(a,0),a);const b=F.advance(a,.125);assert.equal(plain(a),snapshot);assert.ok(b.colonies[0].segments.some((s,i)=>s.xx!==a.colonies[0].segments[i]?.xx));assert.ok(b.time===.125);const s=b.colonies[0].segments.find(s=>s.lastUpdated===b.time);assert.ok(s);assert.equal(F.tipPosition(s,b.time+.125).x,s.xx);check(b);});
test('branching, resources, aging and sustained bounded network',()=>{let w=F.create(21);const initial=w.colonies[0].nextId;for(let i=0;i<960;i++)w=F.advance(w,.125);check(w);assert.ok(w.colonies[0].nextId>initial+100);assert.ok(w.colonies.every(k=>k.tips.length>0));assert.ok(w.colonies.some(k=>k.segments.some(s=>s.fusion)));assert.ok(w.colonies.some(k=>k.nutrients.some(n=>n<.9)));});
test('founder topology varies across specimens without fixed quadrant or depth templates',()=>{const w=F.create(81),counts=new Set(w.colonies.map(k=>k.segments.length));assert.ok(counts.size>5,'different specimens need different topology budgets');const roots=w.colonies.flatMap(k=>k.segments.filter(s=>s.parentId===null));assert.ok(new Set(roots.map(s=>Math.round(Math.atan2(s.y,s.x)*100))).size>70,'founders must not sit on four fixed directions');assert.ok(w.colonies.every(k=>k.segments.every(s=>s.born<=0)));});

test('layer metadata tracks competition and compatible fusion activity',()=>{let w=F.create(8);const start=w;for(let i=0;i<160;i++)w=F.advance(w,.125);for(const k of w.colonies){assert.equal(k.layers.length,25);assert.equal(new Set(k.layers.map(l=>l.family)).size,3);for(const l of k.layers){assert.ok(Object.isFrozen(l));assert.equal(l.population,k.segments.filter(s=>s.lineage===l.id).length);assert.ok(l.activity>=0&&l.activity<=1);assert.ok(l.growthRate>0&&l.branching>0);}}assert.ok(w.colonies.some(k=>k.layers.some(l=>l.fusions>0)));assert.ok(w.colonies[0].layers.some((l,i)=>l.activity!==start.colonies[0].layers[i].activity));});

test('persistent inherited depth extends with spatial growth and interpolates',()=>{const a=F.create(4),b=F.advance(a,.125);const k=a.colonies[0];assert.ok(new Set(k.segments.map(s=>s.zz.toFixed(4))).size>20);for(const s of k.segments){assert.ok(Number.isFinite(s.z)&&Number.isFinite(s.zz)&&Number.isFinite(s.previousZZ));assert.ok(Math.abs(s.zz)<=.4);assert.ok(Number.isFinite(s.pitch)&&Number.isFinite(s.basePhase));}assert.ok(b.colonies[0].segments.some((s,i)=>s.zz!==k.segments[i]?.zz));const s=b.colonies[0].segments.find(s=>s.lastUpdated===b.time);assert.equal(F.tipPosition(s,b.time+.125).z,s.zz);assert.equal(F.tipPosition(s,b.time).z,s.previousZZ);for(const t of b.colonies[0].tips)assert.ok(Number.isFinite(t.z));});
