const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const context=vm.createContext({});vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../habitat.js'),'utf8'),context);const H=context.MicroHabitat;
const specimen=n=>({uid:`cell:${n}`,seed:n,layers:Array.from({length:25},(_,i)=>({genome:{pigmentIdentity:(i+n*31).toString(16),hue:100,pigmentAnchor:100,lightness:.65,chroma:.08}}))});
test('habitats retain stable identity through evolution and theme',()=>{const c=specimen(8),p=H.palette(c);assert.deepEqual(H.palette({...c,dark:true,layers:c.layers.map(l=>({genome:{...l.genome,hue:180,dna:'changed'}}))}),p);assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.hues));});
test('each habitat contains only three coherent families and balanced lineage assignment',()=>{for(let n=0;n<64;n++){const c=specimen(n),colors=c.layers.map((l,i)=>H.pigment(c,l.genome,i));assert.ok(new Set(colors.map(g=>g.habitatFamily)).size<=3);assert.deepEqual(colors.reduce((counts,g)=>(counts[g.habitatFamily]++,counts),[0,0,0]),[13,9,3]);}});
test('gallery covers red orange yellow green blue indigo violet',()=>{const hues=new Set();const names=new Set();for(let n=0;n<256;n++){const p=H.palette(specimen(n));names.add(p.name);p.hues.forEach(h=>hues.add(h));}assert.equal(names.size,8);for(const h of [25,55,95,145,245,280,310])assert.ok(hues.has(h));});
test('pigment clones leave parents unchanged and bound somatic color drift',()=>{const c=specimen(2),g=Object.freeze({...c.layers[0].genome,hue:300});const before=JSON.stringify(c);const out=H.pigment(c,g,0);assert.ok(Object.isFrozen(out));assert.notEqual(out,g);assert.equal(JSON.stringify(c),before);assert.ok(Math.abs(out.habitatHue-H.palette(c).hues[out.habitatFamily])<=7);assert.ok(Math.abs(out.lightness-g.lightness)<.04);assert.ok(Math.abs(out.chroma-g.chroma)<.02);});

test('every nature recipe pairs substantial warm and cool pigment families',()=>{const recipes=new Map();for(let n=0;n<256;n++){const p=H.palette(specimen(n));recipes.set(p.name,p.hues);}assert.equal(recipes.size,8);for(const [name,hues] of recipes){const separation=Math.abs(((hues[0]-hues[1]+540)%360)-180);assert.ok(separation>=110,`${name} needs a distinct secondary pigment`);assert.ok(hues.some(h=>h<=75||h>=335),`${name} needs a warm pigment`);assert.ok(hues.some(h=>h>=140&&h<=280),`${name} needs a cool pigment`);}});
