'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function renderer(){
 const fills=[],strokes=[],images=[],paths=[],lines=[];let cursor={x:0,y:0};
 const g={globalAlpha:1,canvas:{width:400},getTransform:()=>({a:1}),save(){},restore(){},beginPath(){},closePath(){},rect(){},clip(){},moveTo(x,y){cursor={x,y};},lineTo(x,y){lines.push({from:cursor,to:{x,y}});},arc(){},fill(){},stroke(){},strokeRect(){strokes.push(this.strokeStyle)},fillRect(){fills.push({fill:this.fillStyle,composite:this.globalCompositeOperation})},clearRect(){},translate(){},scale(){},rotate(){},drawImage(){},setTransform(){},bezierCurveTo(...p){paths.push(p)},quadraticCurveTo(...p){paths.push(p)}};
 const context={document:{createElement:()=>{const image={width:128,height:128,getContext:()=>g};images.push(image);return image;}},MicroModel:{spring:(v,t)=>({value:t,velocity:0})},MicroFungus:{health:()=>1,tipPosition:s=>({x:s.xx,y:s.yy,z:s.zz})},MicroColor:{css:()=> '#aa8899',ceiling:()=>.2},MicroParticles:{sample:()=>[],step:(old,home)=>({...home,vx:0,vy:0}),lensScale:()=>1.2},MicroView:{geometry:()=>({columns:5,gap:100,left:0,top:0}),origin:c=>({x:c.tileCol*100+50,y:c.tileRow*100+50,size:100}),boundary:c=>({x:c.tileCol*100,y:c.tileRow*100,size:100})},MicroGenome:{describe:()=>({sectors:4})},Generate:{progress:()=>1,reveal(){}},performance:{now:()=>0},Math,Map};context.globalThis=context;vm.runInNewContext(fs.readFileSync(__dirname+'/../flat-geometry.js','utf8'),context);vm.runInNewContext(fs.readFileSync(__dirname+'/../render.js','utf8'),context);
 const colony={id:0,seed:1,tileRow:0,tileCol:0,segments:[],layers:Array.from({length:25},()=>({genome:{lightness:.7,hue:210,chroma:.1}}))};return {context,R:context.MicroRender,g,colony,fills,strokes,images,paths,lines};
}
test('hover stays empty with only one crisp cyan edge',()=>{const {R,g,colony,fills,strokes}=renderer();R.beginFrame(.016,null);R.grid(g,[colony],400,400,0,[{value:1}]);assert.equal(fills.length,0);assert.equal(strokes.length,1);assert.equal(strokes[0],'oklch(.78 .125 205 / .9)');});
test('ripple expires after1.8seconds and reduced motion clears it',()=>{const {R,colony}=renderer();R.beginFrame(.016,null);R.ripple(colony);assert(R.busy());R.beginFrame(1.81,null);assert(!R.busy());R.ripple(colony);R.beginFrame(.016,null,true);assert(!R.busy());});
test('selected specimen uses sharper physical pixel cache without raster lens copies',()=>{const {R,g,colony,images}=renderer();R.beginFrame(.016,{colony:0,x:50,y:50});R.grid(g,[colony],400,400,0,[{value:1}]);assert.equal(images.length,1);assert.equal(images[0].width,256);});
test('petri renderer exposes no sphere backend or rotation controls',()=>{const {R}=renderer();assert.equal(R.rotate,undefined);assert.equal(R.setSphere,undefined);assert.equal(R.stats().backend,'canvas');});
test('obsolete absorption overlay is removed from renderer',()=>{const {R}=renderer();assert.equal(R.merge,undefined);});

test('row opening keeps insertion line fixed and shifts following ruled lines',()=>{const {R,g,lines}=renderer();R.beginFrame(.016,null);R.grid(g,[],400,400,0,[],1,-1,false,{zoom:1,panX:0,panY:0,rowOpening:{row:2,amount:.5}});const horizontal=lines.filter(line=>line.from.y===line.to.y).map(line=>line.to.y);assert(horizontal.includes(200));assert(horizontal.includes(250));assert(horizontal.includes(350));assert(!horizontal.includes(300));});

test('recycled slot regenerates texture for a new identity at frozen simulation time',()=>{const {R,g,colony,paths,lines}=renderer(),genome=colony.layers[0].genome;const first={...colony,uid:'parent',segments:[{id:1,lineage:0,x:.1,y:.1,xx:.4,yy:.2,z:0,zz:0,width:.004,genome,flowSpeed:.01}]};R.beginFrame(.016,null);R.grid(g,[first],400,400,0,[]);paths.length=0;lines.length=0;R.grid(g,[{...first,uid:'child',seed:2}],400,400,0,[]);assert.ok(paths.length>0||lines.length>0);});

test('grid bounds expensive cache refreshes and fairly warms all visible specimens',()=>{const {R,g,colony,images}=renderer(),colonies=Array.from({length:12},(_,id)=>({...colony,id,seed:id+1,tileCol:id%4,tileRow:Math.floor(id/4)}));for(let frame=0;frame<2;frame++){const before=images.length;R.beginFrame(.016,null);R.grid(g,colonies,400,400,frame/10,[]);assert(images.length-before<=6);}assert.equal(images.length,12);});

test('petri previews never allocate a GPU backend',()=>{const {context,R,g,colony}=renderer();context.MicroGPU={draw:()=>{throw new Error('GPU should not run');}};R.beginFrame(.016,null);R.preview(g,colony,160,160,0);assert.equal(R.stats().backend,'canvas');});

test('grid cache refresh respects elapsed interaction work budget',()=>{const {context,R,g,colony,images}=renderer();let clock=0;context.performance.now=()=>clock+=1;const colonies=Array.from({length:12},(_,id)=>({...colony,id,seed:id+1,tileCol:id%4,tileRow:Math.floor(id/4)}));R.beginFrame(.016,null);R.grid(g,colonies,400,400,0,[]);assert(images.length<=4);assert(images.length>0);});

test('flat filaments use one precise stroke with no wide translucent aura',()=>{const {R,g,colony,paths}=renderer();let strokes=0;g.stroke=()=>{if(g.lineWidth<.1)strokes++;};colony.segments=[{id:1,lineage:0,x:.1,y:.1,xx:.3,yy:.2,z:0,zz:0,width:.004,genome:colony.layers[0].genome,flowSpeed:.01}];R.beginFrame(.016,null);R.grid(g,[colony],400,400,0,[]);assert.equal(strokes,1);});
test('flat tissue uses subpixel ink at readable opacity instead of faint chords',()=>{const {R,g,colony}=renderer();const ink=[];g.stroke=()=>ink.push({width:g.lineWidth,alpha:g.globalAlpha});colony.segments=[{id:1,lineage:0,x:.1,y:.1,xx:.3,yy:.2,z:0,zz:0,width:.004,genome:colony.layers[0].genome,flowSpeed:.01}];R.beginFrame(.016,null);R.grid(g,[colony],400,400,0,[]);assert.ok(ink.some(row=>row.alpha>=.7&&row.alpha<1));});
test('flat branches crossing a mirror seam pass through it without a false chord',()=>{const {R,g,colony,lines}=renderer();colony.segments=[{id:1,lineage:0,x:.4,y:-.05,xx:.4,yy:.05,z:0,zz:0,width:.004,genome:colony.layers[0].genome,flowSpeed:.01}];R.beginFrame(.016,null);R.grid(g,[colony],400,400,0,[]);assert.ok(lines.some(line=>Math.abs(line.to.x-.4)<.02&&line.to.y<.004));});

test('flat framing updates as growth expands rather than clipping mature tissue',()=>{const {R,g,colony}=renderer(),scales=[];g.scale=(x,y)=>{if(x>1)scales.push(x);};const segment={id:1,lineage:0,x:.1,y:.1,xx:.2,yy:.1,z:0,zz:0,width:.004,genome:colony.layers[0].genome,flowSpeed:.01};R.beginFrame(.016,null);R.grid(g,[{...colony,segments:[segment]}],400,400,0,[]);const initial=scales[0];scales.length=0;R.beginFrame(.016,null);R.grid(g,[{...colony,segments:[{...segment,xx:.8,yy:.1}]}],400,400,1,[]);assert.ok(scales[0]<initial*.6);});
test('flat paused rendering ignores unfinished sphere warmup',()=>{const {context,R,g,colony}=renderer();context.MicroGPU={stats:()=>({backend:'webgl2',pendingGeneration:100,bytes:0}),setTextureBytes(){}};R.beginFrame(0,null);R.grid(g,[colony],400,400,0,[]);assert.equal(R.busy(),false);});
test('flat transfer anchors follow the same pre-fold cubic as tissue particles',()=>{const {context,R,colony}=renderer(),segment={id:1,lineage:0,x:.4,y:-.05,xx:.4,yy:.05,z:0,zz:0,genome:colony.layers[0].genome};colony.segments=[segment];const expected=context.MicroFlatGeometry.fold(context.MicroFlatGeometry.sample(context.MicroFlatGeometry.curve(segment,{x:segment.xx,y:segment.yy}),.5),Math.PI/4),mag=Math.min(2.8,.82/Math.hypot(segment.xx,segment.yy)),p=R.transferPoint(colony,segment,.5,0,false);assert.ok(Math.abs(p.x-expected.x*mag)<1e-8);assert.ok(Math.abs(p.y-expected.y*mag)<1e-8);});
