const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const c=vm.createContext({});for(const file of ['colors.js','biology.js','genetics.js','field.js','fungal.js','genome.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),c);
const G=c.MicroGenetics;
test('standard code translates all64codons with correct starts/stops and complements',()=>{assert.equal(Object.keys(G.codons).length,64);assert.equal(G.translate('ATGTTTTGGTAA'),'MFW*');assert.equal(G.complement('ATGCCG'),'TACGGC');assert.equal(G.reverseComplement('ATGCCG'),'CGGCAT');assert.throws(()=>G.analyze('X'.repeat(384)),/DNA/);});
test('384nt synthetic DNA reproducibly drives real model traits',()=>{const a=G.create(7,{lightness:.65,chroma:.08,hue:190}),b=G.create(7,{lightness:.65,chroma:.08,hue:190});assert.equal(a.sequence,b.sequence);assert.equal(a.sequence.length,384);assert.equal(a.protein.length,128);assert.ok(Object.isFrozen(a));const rich=G.analyze('GCG'.repeat(128)),poor=G.analyze('ATA'.repeat(128));assert.notEqual(rich.growthRate,poor.growthRate);assert.notEqual(rich.pitch,poor.pitch);const world=c.MicroFungus.create(7);for(const k of world.colonies)for(const l of k.layers){assert.equal(l.genome.sequence.length,384);assert.equal(l.growthRate,l.genome.growthRate);assert.equal(l.branching,l.genome.branchingRate);}for(const s of world.colonies[0].segments){assert.equal(s.pitch,s.genome.pitch);assert.equal(s.lifespan,s.genome.lifespan);}});
test('recombination and seeded mutation preserve parental DNA and inherited phenotype',()=>{const a=G.create(1,{lightness:.65,chroma:.06,hue:210}),b=G.create(2,{lightness:.65,chroma:.08,hue:310});const snapshot=a.sequence,child=G.breed(a,b,9);assert.equal(a.sequence,snapshot);assert.equal(child.sequence.length,384);assert.ok(child.sequence!==a.sequence&&child.sequence!==b.sequence);assert.equal(child.growthRate,G.analyze(child.sequence).growthRate);assert.equal(child.protein,G.translate(child.sequence));assert.ok(Object.isFrozen(child));});
test('genome panel uses selected live layer actual sequence and metrics',()=>{const k=c.MicroFungus.create(6).colonies[0],d=c.MicroGenome.describe(k,17),code=c.MicroGenome.code(k,17);assert.equal(d.sequence,k.layers[17].genome.sequence);assert.equal(d.gc,k.layers[17].genome.gc);assert.ok(code.includes('Illustrative synthetic DNA'));assert.ok(code.includes(d.sequence.slice(0,48)));assert.ok(code.includes(d.protein.slice(0,32)));assert.ok(!code.includes('rabbit'));});
test('reference-backed genomes are distinct seeded synthetic derivatives with replayable substitutions',()=>{const reference=Object.freeze({accession:'TEST.1',sequence:'ACGT'.repeat(96),translationTable:null}),before=JSON.stringify(reference),pigment={lightness:.65,chroma:.08,hue:210};const genomes=Array.from({length:25},(_,i)=>G.create(400+i,pigment,reference));assert.equal(new Set(genomes.map(g=>g.sequence)).size,25);for(const g of genomes){assert.equal(g.synthetic,true);assert.equal(g.sources[0].sequence,reference.sequence);let replay=[...reference.sequence];for(const operation of g.generationTrace.operations){assert.equal(replay[operation.position],operation.from);replay[operation.position]=operation.to;}assert.equal(replay.join(''),g.sequence);assert.equal(G.fingerprint(g.sequence),g.generationTrace.fingerprint);}assert.equal(JSON.stringify(reference),before);assert.equal(JSON.stringify(genomes[4]),JSON.stringify(G.create(404,pigment,reference)));});
test('bootstrap uses supplied final genomes for geometry rather than swapping them onto unrelated topology',()=>{const layers=c.MicroFungus.createLayers(11,0),low=G.analyze('ATA'.repeat(128)),high=G.analyze('GCG'.repeat(128)),replace=genome=>layers.map(l=>({...l,genome:{...l.genome,...genome}}));const a=c.MicroFungus.createColony(11,0,0,{layers:replace(low)}),b=c.MicroFungus.createColony(11,0,0,{layers:replace(high)});assert.notEqual(JSON.stringify(a.segments.map(s=>[s.x,s.y,s.xx,s.yy])),JSON.stringify(b.segments.map(s=>[s.x,s.y,s.xx,s.yy])));assert.ok(a.segments.every(s=>s.genome.sequence===low.sequence&&s.pitch===low.pitch));assert.ok(b.segments.every(s=>s.genome.sequence===high.sequence&&s.pitch===high.pitch));assert.equal(a.generationTrace.version,'topology-genome-v2');});
