const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const c=vm.createContext({});for(const n of ['colors.js','biology.js','view.js','transfer.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',n),'utf8'),c);const T=c.MicroTransfer;
const genome=Object.freeze({hue:200,lightness:.65,chroma:.08}),segments=Array.from({length:12},(_,id)=>({id,x:Math.sin(id)*.2,y:Math.cos(id)*.2,z:.03,xx:Math.sin(id)*.3,yy:Math.cos(id)*.3,zz:.06,lineage:id%3,genome,width:.004}));
const parents=[{id:0,uid:'a',tileRow:0,tileCol:0,size:1,segments},{id:1,uid:'b',tileRow:0,tileCol:1,size:1,segments}];const child={id:2,uid:'c',tileRow:1,tileCol:1,size:1,seed:34,segments,ancestry:[{uid:'a',weight:.6},{uid:'b',weight:.4}]};const reservation={before:{time:0,colonies:parents},child,id:2,parentAId:0,parentBId:1,row:1};const camera={zoom:1,panX:0,panY:0};
test('deterministic cached stable ancestryweighted samples boundedbudget',()=>{const p=T.prepare(reservation);assert.equal(p,T.prepare(reservation));assert.ok(Object.isFrozen(p));assert.equal(new Set(p.targets.map(t=>t.id)).size,p.targets.length);assert.ok(p.targets.length<=256);const a=p.targets.filter(t=>t.parentIndex===0).length;assert.ok(Math.abs(a/p.targets.length-.6)<.06);assert.ok(p.targets.some(t=>t.parentIndex===1));});
test('continuous endpoints and finite bounded velocities without specimen mutation',()=>{const snapshot=JSON.stringify(reservation),p=T.prepare(reservation);let previous=T.frame(p,reservation,[...parents,child],800,800,camera,.6);for(let time=.61;time<=2.3;time+=.01){const f=T.frame(p,reservation,[...parents,child],800,800,camera,time);assert.equal(f.particles.length,p.targets.length);for(let i=0;i<f.particles.length;i++){const q=f.particles[i];assert.ok(Number.isFinite(q.x)&&Number.isFinite(q.y)&&Number.isFinite(q.vx));assert.ok(Math.hypot(q.vx,q.vy)<5000);assert.ok(Math.hypot(q.x-previous.particles[i].x,q.y-previous.particles[i].y)<80);}previous=f;}const end=T.frame(p,reservation,[...parents,child],800,800,camera,1.6,{membrane:true}),after=T.frame(p,reservation,[...parents,child],800,800,camera,2.25);assert.equal(end.particles[0].x,after.particles[0].x);assert.equal(JSON.stringify(reservation),snapshot);assert.ok(end.membrane.outline.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));});
test('cancellation yields empty frame and leaves source objects intact',()=>{const p=T.prepare({...reservation,child:{...child,uid:'cancel'}});T.cancel(p);const f=T.frame(p,reservation,parents,800,800,camera,1);assert.equal(f.particles.length,0);assert.equal(parents[0].uid,'a');});

test('offscreen source ports preserve parents while bounding visible velocity and flat endpoint mode',()=>{const far={...parents[0],tileCol:-50000,tileRow:-50000};const r={...reservation,before:{time:0,colonies:[far,parents[1]]},child:{...child,uid:'far'}};const p=T.prepare(r);for(let time=.6;time<=1.6;time+=.025){const f=T.frame(p,r,[far,parents[1],r.child],800,800,camera,time,{sphere:false});assert.ok(f.particles.every(q=>Math.hypot(q.vx,q.vy)<=f.velocityLimit));for(const curve of f.curves){assert.ok(curve.from.x>=12&&curve.from.x<=788);assert.ok(curve.from.y>=12&&curve.from.y<=788);}}assert.equal(far.tileCol,-50000);});

test('transfer alpha complements child reveal at arrival, midpoint and completion',()=>{const p=T.prepare(reservation),frames=[1.6,1.925,2.25].map(t=>T.frame(p,reservation,[...parents,child],800,800,camera,t));assert.equal(frames[0].particles[0].alpha,1);assert.ok(Math.abs(frames[1].particles[0].alpha-.5)<1e-10);assert.equal(frames[2].particles[0].alpha,0);for(const f of frames){assert.ok(Math.abs(f.particles[0].alpha+f.reveal-1)<1e-10);assert.equal(f.particles[0].x,frames[0].particles[0].x);assert.equal(f.particles[0].y,frames[0].particles[0].y);}});
test('renderer endpoint contract uses the petri coordinate path',()=>{c.MicroRender={specimenRadius:size=>size*.405,transferPoint:()=>({x:.4,y:.3,z:0})};const r={...reservation,child:{...child,uid:'petri-contract'}};const plan=T.prepare(r),f=T.frame(plan,r,[...parents,child],800,800,camera,.6);const origin=c.MicroView.origin(parents[plan.targets[0].parentIndex],800,800,camera);assert.ok(Math.abs(f.particles[0].x-(origin.x+.4*origin.size*.405))<1e-10);delete c.MicroRender;});

test('coherent layer bundles retain stable arrival identities with staggered release',()=>{const r={...reservation,child:{...child,uid:'bundles'}},p=T.prepare(r);assert.ok(p.targets.every(t=>Number.isFinite(t.release)&&t.release>=0&&t.release<=.12));assert.ok(new Set(p.targets.map(t=>t.bundle)).size>=2);const a=T.frame(p,r,[...parents,r.child],800,800,camera,1.59),b=T.frame(p,r,[...parents,r.child],800,800,camera,1.6);for(let i=0;i<a.particles.length;i++){assert.equal(a.particles[i].id,b.particles[i].id);assert.ok(Math.hypot(a.particles[i].x-b.particles[i].x,a.particles[i].y-b.particles[i].y)<1);}assert.ok(p.targets.every(t=>t.stratum>=0&&t.stratum<125));});

test('handoff target segments belong to the unchanged child topology',()=>{const p=T.prepare(reservation),ids=new Set(child.segments.map(segment=>segment.id));assert.ok(p.targets.every(target=>ids.has(target.childSegmentId)));});
test('Canvas fallback shares gamut-safe theme pigments in light and dark modes',()=>{for(const dark of [false,true]){const ctx={save(){},restore(){},beginPath(){},arc(){},fill(){}};T.draw(ctx,{particles:[{x:1,y:2,radius:1,alpha:.37,genome}]},{dark});const d=c.MicroColor.displayPigment(genome,dark);assert.equal(ctx.fillStyle,c.MicroColor.css(d.lightness,d.chroma,d.hue));assert.equal(ctx.globalAlpha,.37);assert.ok(d.chroma<=c.MicroColor.ceiling(d.lightness,d.hue)+1e-10);assert.equal(c.MicroColor.displayPigment(genome,!dark).hue,d.hue);}});
